apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-deployment-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-python-app-prod
  template:
    metadata:
      labels:
        app: my-python-app-prod
    spec:
      containers:
      - name: mypythondockeraksrepo
        image: capstoneprojectacr.azurecr.io/sureshmr/mypythondockeraksrepo:5
        ports:
        - containerPort: 5000
# service type loadbalancer added      
---
apiVersion: v1
kind: Service
metadata:
  name: my-python-app-svc-prod
spec:
  selector:
    app: my-python-app-prod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
